### ISSUE TITLE
possible Null reference on line 273

### ISSUE THREAD

**Issue by 0ptera** [justarandomgeek/nixie-tubes#1]
When loaded on fresh game for _,surf in pairs(global.nixie_tubes.nixies) do causes a null reference exception since global.nixie_tubes doesn't exist.

Fix: 
`script.on_configuration_changed(function(data)
  if data.mod_changes and data.mod_changes["nixie-tubes"] then
    global.controllers = {}
    global.states = {}
    global.spriteobjs = {}
    global.nextdigit = {}
    if global.nixie_tubes then
        for _,surf in pairs(global.nixie_tubes.nixies) do
          for _,row in pairs(surf) do
            for _,desc in pairs(row) do
              if desc.entities[1] and desc.entities[1].valid then
                for _,s in pairs(desc.spriteobjs) do if s.valid then s.clear_items_inside() s.destroy() end end
                onPlaceEntity({created_entity=desc.entities[1]})
              end  
            end
          end
        end
        global.nixie_tubes = nil
    end
  end
end)`

**Comment by justarandomgeek** [comment]
Yeah, I discovered this last night and fixed it on my local system. I'll post a new build later today with this fix. Side effect of being polite and moving migration to on_configuration_changed, i ended up never actually initializing things when loaded the first time in a save!

**Comment by justarandomgeek** [comment]
0.2.4 should resolve this.
