### ISSUE TITLE
.15 Can remove the fake car and use simple-entity-force  with graphical variants

### ISSUE THREAD

**Issue by Nexela** [justarandomgeek/nixie-tubes#11]
Take a look at luaEntity.graphical_variant

**Comment by justarandomgeek** [comment]
I'm actually hoping I can use variants on the lamps themselves, so I can quit messing with the color signals entirely - I just haven't had a chance to poke at the lamps enough to see if they'll do it.

**Comment by justarandomgeek** [comment]
It seems that none of the simple-entity types support color, so we're still stuck with car+characters for now :(

**Comment by tuxmark5** [comment]
What about the small/double-digit nixie tubes that are non-colored?

**Comment by justarandomgeek** [comment]
All nixies support colors now (they got colors for free in one of the recent updates adding more printing formats).

**Comment by tuxmark5** [comment]
Ah. I'm still sitting on 0.14.*. What about having a separate monochrome version of the nixie entity? It may be worthwhile to include it, assuming the performance would improve when using a large number of nixie displays.

**Comment by justarandomgeek** [comment]
The 0.15 version has some performance improvements anyway, and adjustable update rate, which together make the performance impact mostly a moot point, so I'll probably stick with the car/driver hack until simple-entities support coloring. (Though, I do plan to switch when possible for 'cleanliness'!)

**Comment by tuxmark5** [comment]
Good to know. Thanks for the info.
