### ISSUE TITLE
on_tick: invalid key to 'next'

### ISSUE THREAD

**Issue by doktorstick** [justarandomgeek/nixie-tubes#12]
Nn = nixie tube
```
N1N2 N3
```
Have a N3 powered and a wire connected to it. N1 and N2 are unpowered (this probably doesn't matter). N3 should be configured to show a count. Move N1 into the space between N2 and N3, thereby connecting all the nixie-tubes.

Profit.

```
Error while running event nixie-tubes::on_tick (ID 0)
invalid key to 'next'
```

**Comment by justarandomgeek** [comment]
Were you able to reliably reproduce this? this has been happening semi-randomly for a while but I haven't managed to track down a repro to be able to properly fix it.
