### ISSUE TITLE
Crash when removing large in-use numerical display

### ISSUE THREAD

**Issue by HactarCE** [justarandomgeek/nixie-tubes#16]
Using 0.16.3, there seems to be a crash when parts of a relatively large numerical display are removed while it is live. It does not seem to happen with displays only 1-2 entities wide, but it does occur with displays at least 10 wide. It does not seem to matter whether the entity removed is actually displaying a number; only whether it is part of a larger display that is collectively displaying a number. Attached are two crash "notices."

Error 1:
![long crash](https://user-images.githubusercontent.com/6060305/34064655-cb49ef58-e1c8-11e7-9aa2-c50a5c725b1f.png)

Error 2:
![short crash](https://user-images.githubusercontent.com/6060305/34064731-76cdb45e-e1c9-11e7-85da-7ebcdb02aa8a.png)

Tested in Sandbox mode with the following other mods (though they shouldn't make a difference):
- Auto Trash
- Equipment Hotkeys
- LTN - Logistic Train Network
- Pushbutton
- Skip first hour
- Squeak Through
- Vehicle Snap

**Comment by justarandomgeek** [comment]
Not sure how that slipped through... fixed now in nixies 0.16.1!
