### ISSUE TITLE
Change update speed to lower UPS

### ISSUE THREAD

**Issue by Corncooker** [justarandomgeek/nixie-tubes#21]
I tried changing the speed value in settings.lua. but nothing made a diffrence.  Is there a way to lower the update?

**Comment by justarandomgeek** [comment]
Setting everythign to 1 is the lowest speed. How about some more detail about the actual problem you're having?

**Comment by Corncooker** [comment]
wasnt a problem, just dont need the fast response in my case.  was looking to smooth the display, or at least refresh at a much lower rate.
I love the look, and showing an ore patch of 6 million.  i rounded with a arithmatic (/1000) to show a smaller value eg. 6000K .   the lack of a comma made me build a (6M000K000) . just easier to see. Would like to see (6,000 Million Copper).
Anyway, that doesnt need an update each tick.

**Comment by justarandomgeek** [comment]
Bah, i just now noticed you mentioned settings.lua. There are in-game settings on the mods menu in options, which is what you should be adjusting.

**Comment by Corncooker** [comment]
omg, lol, shoulda checked with options, before trying to do it the hard way. thanks
