### ISSUE TITLE
Pass along remaining Digits

### ISSUE THREAD

**Issue by Saevon** [justarandomgeek/nixie-tubes#22]
Adding thousands separators (or similar numerical dividers) requires a surprising amount of logic, trying to make a clear display results in a lot of trailing wires & combinators.

Thus I suggest having the last nixie send the remaining value to the wires. (aka if you wire to the 3rd nixie, it divides by 1000, the 2nd would divide by 100, etc)

E.g.

Input 1,334,233
First 3 Nixies Show: 223, and pass along 1,334 (wired to the next set)
Next 3 Nixies Show: 334 and pass along 1

**Comment by justarandomgeek** [comment]
Nixie tubes are lamps, and thus cannot output signals only consume them.
