### ISSUE TITLE
Issue when loading the game, was fine before the latest update.

### ISSUE THREAD

**Issue by fefocwb** [justarandomgeek/nixie-tubes#27]
Tryed to load my game after the last update and got this:

![image](https://user-images.githubusercontent.com/17379491/62828587-b4074100-bbc0-11e9-88a9-4a07f68c83ea.png)

**Comment by justarandomgeek** [comment]
post your save

**Comment by fefocwb** [comment]
Try to get it from here

[https://drive.google.com/drive/folders/1o9nYE9i9yWwRpk6mkpPA0Qv4lyuOldWT?usp=sharing](url)

**Comment by justarandomgeek** [comment]
Apparently my test world happened to build things in the order that let me update them right away as they're built - yours were built in a different order, so it doesn't! I'll make another update in a couple minutes to fix this.

**Comment by fefocwb** [comment]
Thanks a lot man... appreciate your attention... :)
