### ISSUE TITLE
Merging Networks Doubles Signals

### ISSUE THREAD

**Issue by jmurrayufo** [justarandomgeek/nixie-tubes#3]
Issue: Merging a networks in play doubles already displayed signals on Nixie Tubes. Reset of game clears condition

Reproduction Steps:
1. A minimum of 3 nixie tubes, placed such that they do NOT merge into a display. We need to be able to destroy and place one, and still have a 'sub network' left behind. Placing three vertically works well. 
2. Place target item into a set of chests, again with enough chests that separating the displays leaves a functional circuit network behind and still counting items. 
3. Merge the networks. The display value on the tubes will be added to the items seen in the chests. 

Other notes:
Reproduced on 0.13.13 with otherwise clean install and cheated in tubes. 
Reloading a save clears the issues, no math errors. 
Works with small and numeric tubes, haven't thought of a way to reproduce on alpha tubes.

**Comment by justarandomgeek** [comment]
Alphas don't link between units, so probably will not have this problem. I'll do some testing shortly...

**Comment by justarandomgeek** [comment]
I can't seem to repro this, it may have been fixed by the set of changes I had not yet released. I'm about to post 0.2.6. Can you test if this resolves the issue for you?

**Comment by jmurrayufo** [comment]
Sure, i'll keep an eye out for the update to hit and see if that fixes it.

**Comment by jmurrayufo** [comment]
Issue exists in 0.2.6, taking a quick series of photos to show exactly what I am seeing and doing.

First we setup a simple network, 3 nixie tubes, 3 chests. I throw some circuits (100 each) into the chests to get a display. Here we see it acting as expected. 
![2016-07-31 12_59_28-factorio 0 13 13](https://cloud.githubusercontent.com/assets/442011/17278631/c2a60ebc-571e-11e6-8e24-1a88834452bb.png)

Now lets delete the connection point, splitting the network into two parts. We see that despite no connection to the chest, the nixie tubes KEEP there values displayed. Checking a power pole confirms that the circuit network on the left has a signal of 100 green/red circuits each. 
![2016-07-31 12_59_31-factorio 0 13 13](https://cloud.githubusercontent.com/assets/442011/17278642/eb39de30-571e-11e6-8821-fcac5cf6cfee.png)

Okay, now lets replace that nixie tube and connect it up. Presto! We have doubled the number of circuits! 
![2016-07-31 12_59_44-factorio 0 13 13](https://cloud.githubusercontent.com/assets/442011/17278654/26433742-571f-11e6-89c7-4c37d20f558b.png)

Repeating doubles the signal again. 
![2016-07-31 13_02_36-factorio 0 13 13](https://cloud.githubusercontent.com/assets/442011/17278655/316f8a80-571f-11e6-82f0-87d7806f26ca.png)

These steps were done on an un-modded game, short of your mod and the base game.

**Comment by justarandomgeek** [comment]
Oh that's bizarre! Almost certainly related to my recent rewrite of the linking code. I'm away from my computer now, but will have another look tonight/tomorrow.

**Comment by jmurrayufo** [comment]
No worries. As I said, a reload of the game fixes the issue. The boot up code handles it correctly (no network was every merged). This is really only an issue when making changes to the network. I have a workaround, so I am peachy happy for now.

**Comment by jmurrayufo** [comment]
Looks like they might have closed this one from the game side. I never checked it vs your mod. 

https://forums.factorio.com/viewtopic.php?t=30167

**Comment by justarandomgeek** [comment]
~~Well, later than intended, but I sat down and tried to repro this again and I simply can't make mine do this! I followed your screenshots exactly, and as soon as I remove the corner block they lower two rows reset back to 0, and then continue to perform as expected when reconnected.~~ I didnt' see your comment until posting this one. That's clearly the source of it, it works fine now!
