### ISSUE TITLE
Numeric Nixie do not support special signals

### ISSUE THREAD

**Issue by doktorstick** [justarandomgeek/nixie-tubes#4]
... or I'm not understanding it.

I have a setup that displays the level of a tank. It takes four nixie tubes and two deciders. The deciders have the logic:

```
if EACH < 1000, output RED input count
if EACH > 999, output GREEN input count
```

I have a red wire going from the tank to an input on each decider. I have a green wire going from each decider to the right-most nixie tube. The nixie tube has "use colors" and an enabled condition. It's this enabled condition that I take issue with.

If I set the enabled condition to ANYTHING or EVERYTHING, the nixie tube only displays 0 even though (in my current setup) the output from the deciders is GREEN 2.4k.

I can set the nixie tube to GREEN and it will display the 2.4K until it drops below 1000, and then the RED signal takes over and 0 is displayed (even though its > 0).

How I've been able to get it to work is to add a second green line from the tank to the nixie tube and set the nixie tube to the tank's contents (i.e., petro for petro, light oil for light, etc. etc.), but it's inconvenient, and I would think ANYTHING or EVERYTHING would do the trick.

**Comment by justarandomgeek** [comment]
Any/Every signals require special handling that I don't currently do (I expected nixies to always display a specific value). Simplest workaround for now is probably to use an arithmetic combinator doing special+0=>(arbitrarily chosen regular signal) and display the output of that. I'll see if I can handle Any/Every intelligently.

**Comment by sparr** [comment]
For ANY and EVERY, what is the expected behavior if multiple signals are coming in? maybe ANY is MAX and EVERY is SUM?

**Comment by justarandomgeek** [comment]
What's the usecase for nixies that aren't on a fixed signal?

**Comment by sparr** [comment]
original issue mentioned wanting to measure the amount of fluid in a tank, which could be any different fluid signal.

**Comment by justarandomgeek** [comment]
My main objection to doing this is that you can fairly trivially get any fluid in a tank onto a known signal using the combinator I described previously (which is also `sum()`), while doing `max()`/`sum()` in lua will end up being pretty slow (in an already-heavy mod), especially when someone decides to plug their whole lognet into it.
