### ISSUE TITLE
Enhancement for booting drivers out of nixies

### ISSUE THREAD

**Issue by Nexela** [justarandomgeek/nixie-tubes#6]
This slight change below will kick the player out to the the place they entered from.  Current version sends them crabwalking down the line ;)

script.on_event(defines.events.on_player_driving_changed_state,
    function(event)
      local player=game.players[event.player_index]
      if player.vehicle and
        (player.vehicle.name=="nixie-tube-sprite" or
          player.vehicle.name=="nixie-tube-small-sprite") then
          player.vehicle.passenger = false
          player.teleport(player.position)
      end
    end
)

**Comment by justarandomgeek** [comment]
This is essentially a moot point now due to all the cars having a colorman in them.
